################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
common/button_if.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common/button_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="common/button_if.pp" --obj_directory="common" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/gpio_if.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common/gpio_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="common/gpio_if.pp" --obj_directory="common" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/i2c_if.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common/i2c_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="common/i2c_if.pp" --obj_directory="common" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/startup_ccs.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common/startup_ccs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="common/startup_ccs.pp" --obj_directory="common" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/timer_if.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common/timer_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="common/timer_if.pp" --obj_directory="common" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/udma_if.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common/udma_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="common/udma_if.pp" --obj_directory="common" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/wdt_if.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common/wdt_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="common/wdt_if.pp" --obj_directory="common" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


