# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='audio_data.proto',
  package='',
  serialized_pb='\n\x10\x61udio_data.proto\"|\n\naudio_data\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x01(\x0c\x12\x17\n\x0f\x66\x65\x61ture_version\x18\x02 \x01(\x05\x12\x0f\n\x07samples\x18\x03 \x01(\x05\x12\x0c\n\x04rate\x18\x04 \x01(\x05\x12\x15\n\raudio_version\x18\x05 \x01(\x05\x12\r\n\x05\x61udio\x18\x06 \x01(\x0c')




_AUDIO_DATA = _descriptor.Descriptor(
  name='audio_data',
  full_name='audio_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='audio_data.features', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_version', full_name='audio_data.feature_version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samples', full_name='audio_data.samples', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='audio_data.rate', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='audio_version', full_name='audio_data.audio_version', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='audio', full_name='audio_data.audio', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['audio_data'] = _AUDIO_DATA

class audio_data(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUDIO_DATA

  # @@protoc_insertion_point(class_scope:audio_data)


# @@protoc_insertion_point(module_scope)
