# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncResponse.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SyncResponse.proto',
  package='',
  serialized_pb='\n\x12SyncResponse.proto\"\xf0\x07\n\x0cSyncResponse\x12\x14\n\x0cupload_cycle\x18\x01 \x01(\x05\x12\x12\n\nsync_cycle\x18\x02 \x01(\x05\x12\x15\n\racc_scan_cyle\x18\x03 \x01(\x05\x12\x1d\n\x15\x61\x63\x63_sampling_interval\x18\x04 \x01(\x05\x12 \n\x18\x64\x65vice_sampling_interval\x18\x05 \x01(\x05\x12\"\n\x05\x61larm\x18\x06 \x01(\x0b\x32\x13.SyncResponse.Alarm\x12\x33\n\x0epairing_action\x18\x07 \x01(\x0b\x32\x1b.SyncResponse.PairingAction\x12-\n\x0bwhite_noise\x18\x08 \x01(\x0b\x32\x18.SyncResponse.WhiteNoise\x12/\n\x0c\x66lash_action\x18\t \x01(\x0b\x32\x19.SyncResponse.FlashAction\x12\x14\n\x0creset_device\x18\n \x01(\x08\x1az\n\x05\x41larm\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x05\x12\x16\n\x0bringtone_id\x18\x03 \x01(\x05:\x01\x31\x12\x1c\n\x14ring_offset_from_now\x18\x04 \x01(\x05\x12\x15\n\rring_duration\x18\x05 \x01(\x05\x1aw\n\rPairingAction\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x34\n\x04type\x18\x02 \x01(\x0e\x32&.SyncResponse.PairingAction.ActionType\"\"\n\nActionType\x12\x08\n\x04PAIR\x10\x00\x12\n\n\x06UNPAIR\x10\x01\x1a\x44\n\nWhiteNoise\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x05\x12\x10\n\x08sound_id\x18\x03 \x01(\x05\x1a\xd3\x02\n\x0b\x46lashAction\x12\x32\n\x05led_1\x18\x01 \x01(\x0b\x32#.SyncResponse.FlashAction.LEDAction\x12\x32\n\x05led_2\x18\x02 \x01(\x0b\x32#.SyncResponse.FlashAction.LEDAction\x12\x32\n\x05led_3\x18\x03 \x01(\x0b\x32#.SyncResponse.FlashAction.LEDAction\x12\x32\n\x05led_4\x18\x04 \x01(\x0b\x32#.SyncResponse.FlashAction.LEDAction\x12\x32\n\x05led_5\x18\x05 \x01(\x0b\x32#.SyncResponse.FlashAction.LEDAction\x1a@\n\tLEDAction\x12\r\n\x05\x63olor\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x05')



_SYNCRESPONSE_PAIRINGACTION_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='SyncResponse.PairingAction.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PAIR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNPAIR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=585,
  serialized_end=619,
)


_SYNCRESPONSE_ALARM = _descriptor.Descriptor(
  name='Alarm',
  full_name='SyncResponse.Alarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='SyncResponse.Alarm.start_time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='SyncResponse.Alarm.end_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ringtone_id', full_name='SyncResponse.Alarm.ringtone_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ring_offset_from_now', full_name='SyncResponse.Alarm.ring_offset_from_now', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ring_duration', full_name='SyncResponse.Alarm.ring_duration', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=376,
  serialized_end=498,
)

_SYNCRESPONSE_PAIRINGACTION = _descriptor.Descriptor(
  name='PairingAction',
  full_name='SyncResponse.PairingAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='SyncResponse.PairingAction.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='SyncResponse.PairingAction.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYNCRESPONSE_PAIRINGACTION_ACTIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=500,
  serialized_end=619,
)

_SYNCRESPONSE_WHITENOISE = _descriptor.Descriptor(
  name='WhiteNoise',
  full_name='SyncResponse.WhiteNoise',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='SyncResponse.WhiteNoise.start_time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='SyncResponse.WhiteNoise.end_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sound_id', full_name='SyncResponse.WhiteNoise.sound_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=621,
  serialized_end=689,
)

_SYNCRESPONSE_FLASHACTION_LEDACTION = _descriptor.Descriptor(
  name='LEDAction',
  full_name='SyncResponse.FlashAction.LEDAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='SyncResponse.FlashAction.LEDAction.color', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='SyncResponse.FlashAction.LEDAction.start_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='SyncResponse.FlashAction.LEDAction.end_time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=967,
  serialized_end=1031,
)

_SYNCRESPONSE_FLASHACTION = _descriptor.Descriptor(
  name='FlashAction',
  full_name='SyncResponse.FlashAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='led_1', full_name='SyncResponse.FlashAction.led_1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='led_2', full_name='SyncResponse.FlashAction.led_2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='led_3', full_name='SyncResponse.FlashAction.led_3', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='led_4', full_name='SyncResponse.FlashAction.led_4', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='led_5', full_name='SyncResponse.FlashAction.led_5', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SYNCRESPONSE_FLASHACTION_LEDACTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=692,
  serialized_end=1031,
)

_SYNCRESPONSE = _descriptor.Descriptor(
  name='SyncResponse',
  full_name='SyncResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upload_cycle', full_name='SyncResponse.upload_cycle', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sync_cycle', full_name='SyncResponse.sync_cycle', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc_scan_cyle', full_name='SyncResponse.acc_scan_cyle', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc_sampling_interval', full_name='SyncResponse.acc_sampling_interval', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_sampling_interval', full_name='SyncResponse.device_sampling_interval', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm', full_name='SyncResponse.alarm', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pairing_action', full_name='SyncResponse.pairing_action', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='white_noise', full_name='SyncResponse.white_noise', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flash_action', full_name='SyncResponse.flash_action', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reset_device', full_name='SyncResponse.reset_device', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SYNCRESPONSE_ALARM, _SYNCRESPONSE_PAIRINGACTION, _SYNCRESPONSE_WHITENOISE, _SYNCRESPONSE_FLASHACTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=1031,
)

_SYNCRESPONSE_ALARM.containing_type = _SYNCRESPONSE;
_SYNCRESPONSE_PAIRINGACTION.fields_by_name['type'].enum_type = _SYNCRESPONSE_PAIRINGACTION_ACTIONTYPE
_SYNCRESPONSE_PAIRINGACTION.containing_type = _SYNCRESPONSE;
_SYNCRESPONSE_PAIRINGACTION_ACTIONTYPE.containing_type = _SYNCRESPONSE_PAIRINGACTION;
_SYNCRESPONSE_WHITENOISE.containing_type = _SYNCRESPONSE;
_SYNCRESPONSE_FLASHACTION_LEDACTION.containing_type = _SYNCRESPONSE_FLASHACTION;
_SYNCRESPONSE_FLASHACTION.fields_by_name['led_1'].message_type = _SYNCRESPONSE_FLASHACTION_LEDACTION
_SYNCRESPONSE_FLASHACTION.fields_by_name['led_2'].message_type = _SYNCRESPONSE_FLASHACTION_LEDACTION
_SYNCRESPONSE_FLASHACTION.fields_by_name['led_3'].message_type = _SYNCRESPONSE_FLASHACTION_LEDACTION
_SYNCRESPONSE_FLASHACTION.fields_by_name['led_4'].message_type = _SYNCRESPONSE_FLASHACTION_LEDACTION
_SYNCRESPONSE_FLASHACTION.fields_by_name['led_5'].message_type = _SYNCRESPONSE_FLASHACTION_LEDACTION
_SYNCRESPONSE_FLASHACTION.containing_type = _SYNCRESPONSE;
_SYNCRESPONSE.fields_by_name['alarm'].message_type = _SYNCRESPONSE_ALARM
_SYNCRESPONSE.fields_by_name['pairing_action'].message_type = _SYNCRESPONSE_PAIRINGACTION
_SYNCRESPONSE.fields_by_name['white_noise'].message_type = _SYNCRESPONSE_WHITENOISE
_SYNCRESPONSE.fields_by_name['flash_action'].message_type = _SYNCRESPONSE_FLASHACTION
DESCRIPTOR.message_types_by_name['SyncResponse'] = _SYNCRESPONSE

class SyncResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Alarm(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SYNCRESPONSE_ALARM

    # @@protoc_insertion_point(class_scope:SyncResponse.Alarm)

  class PairingAction(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SYNCRESPONSE_PAIRINGACTION

    # @@protoc_insertion_point(class_scope:SyncResponse.PairingAction)

  class WhiteNoise(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SYNCRESPONSE_WHITENOISE

    # @@protoc_insertion_point(class_scope:SyncResponse.WhiteNoise)

  class FlashAction(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType

    class LEDAction(_message.Message):
      __metaclass__ = _reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _SYNCRESPONSE_FLASHACTION_LEDACTION

      # @@protoc_insertion_point(class_scope:SyncResponse.FlashAction.LEDAction)
    DESCRIPTOR = _SYNCRESPONSE_FLASHACTION

    # @@protoc_insertion_point(class_scope:SyncResponse.FlashAction)
  DESCRIPTOR = _SYNCRESPONSE

  # @@protoc_insertion_point(class_scope:SyncResponse)


# @@protoc_insertion_point(module_scope)
