/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Mon Jun 06 11:32:01 2016. */

#ifndef PB_ASYNC_PB_H_INCLUDED
#define PB_ASYNC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _Ack {
    pb_callback_t message_id;
} Ack;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Ack_init_default                         {{{NULL}, NULL}}
#define Ack_init_zero                            {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Ack_message_id_tag                       1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Ack_fields[2];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
