/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Mon Jun 06 11:32:01 2016. */

#include "async.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Ack_fields[2] = {
    PB_FIELD(  1, UINT64  , REPEATED, CALLBACK, FIRST, Ack, message_id, message_id, 0),
    PB_LAST_FIELD
};


