/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9-dev at Tue Aug 26 07:33:59 2014. */

#include "audio_data.pb.h"



const pb_field_t audio_data_fields[7] = {
    PB_FIELD2(  1, BYTES   , OPTIONAL, CALLBACK, FIRST, audio_data, features, features, 0),
    PB_FIELD2(  2, INT32   , OPTIONAL, STATIC  , OTHER, audio_data, feature_version, features, 0),
    PB_FIELD2(  3, INT32   , OPTIONAL, STATIC  , OTHER, audio_data, samples, feature_version, 0),
    PB_FIELD2(  4, INT32   , OPTIONAL, STATIC  , OTHER, audio_data, rate, samples, 0),
    PB_FIELD2(  5, INT32   , OPTIONAL, STATIC  , OTHER, audio_data, audio_version, rate, 0),
    PB_FIELD2(  6, BYTES   , OPTIONAL, CALLBACK, OTHER, audio_data, audio, audio_version, 0),
    PB_LAST_FIELD
};


