/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Wed Nov  2 15:35:58 2016. */

#include "audio_features_control.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AudioFeaturesControl_fields[2] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, AudioFeaturesControl, enable_keyword_features, enable_keyword_features, 0),
    PB_LAST_FIELD
};


