/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Tue Aug 30 16:29:53 2016. */

#include "audio_commands.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t StopAudio_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, StopAudio, fade_out_duration_seconds, fade_out_duration_seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t PlayAudio_fields[7] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, PlayAudio, file_path, file_path, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, PlayAudio, volume_percent, file_path, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, PlayAudio, duration_seconds, volume_percent, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, PlayAudio, fade_in_duration_seconds, duration_seconds, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, PlayAudio, fade_out_duration_seconds, fade_in_duration_seconds, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, PlayAudio, timeout_fade_out_duration_seconds, fade_out_duration_seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t Volume_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Volume, volume, volume, 0),
    PB_LAST_FIELD
};


