/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Thu Feb 04 12:03:56 2016. */

#ifndef PB_AUDIO_COMMANDS_PB_H_INCLUDED
#define PB_AUDIO_COMMANDS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _PlayAudio {
    pb_callback_t file_path;
    uint32_t volume_percent;
    bool has_duration_seconds;
    uint32_t duration_seconds;
    uint32_t fade_in_duration_seconds;
    uint32_t fade_out_duration_seconds;
} PlayAudio;

typedef struct _StopAudio {
    uint32_t fade_out_duration_seconds;
} StopAudio;

/* Default values for struct fields */

/* Initializer values for message structs */
#define StopAudio_init_default                   {0}
#define PlayAudio_init_default                   {{{NULL}, NULL}, 0, false, 0, 0, 0}
#define StopAudio_init_zero                      {0}
#define PlayAudio_init_zero                      {{{NULL}, NULL}, 0, false, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PlayAudio_file_path_tag                  1
#define PlayAudio_volume_percent_tag             2
#define PlayAudio_duration_seconds_tag           3
#define PlayAudio_fade_in_duration_seconds_tag   4
#define PlayAudio_fade_out_duration_seconds_tag  5
#define StopAudio_fade_out_duration_seconds_tag  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t StopAudio_fields[2];
extern const pb_field_t PlayAudio_fields[6];

/* Maximum encoded size of messages (where known) */
#define StopAudio_size                           6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
