/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Thu Oct 06 10:44:53 2016. */

#ifndef PB_AUDIO_COMMANDS_PB_H_INCLUDED
#define PB_AUDIO_COMMANDS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _PlayAudio {
    char file_path[64];
    uint32_t volume_percent;
    bool has_duration_seconds;
    uint32_t duration_seconds;
    uint32_t fade_in_duration_seconds;
    uint32_t fade_out_duration_seconds;
    bool has_timeout_fade_out_duration_seconds;
    uint32_t timeout_fade_out_duration_seconds;
} PlayAudio;

typedef struct _StopAudio {
    uint32_t fade_out_duration_seconds;
} StopAudio;

typedef struct _VoiceControl {
    bool enable;
} VoiceControl;

typedef struct _Volume {
    uint32_t volume;
} Volume;

/* Default values for struct fields */

/* Initializer values for message structs */
#define StopAudio_init_default                   {0}
#define PlayAudio_init_default                   {"", 0, false, 0, 0, 0, false, 0}
#define Volume_init_default                      {0}
#define VoiceControl_init_default                {0}
#define StopAudio_init_zero                      {0}
#define PlayAudio_init_zero                      {"", 0, false, 0, 0, 0, false, 0}
#define Volume_init_zero                         {0}
#define VoiceControl_init_zero                   {0}

/* Field tags (for use in manual encoding/decoding) */
#define PlayAudio_file_path_tag                  1
#define PlayAudio_volume_percent_tag             2
#define PlayAudio_duration_seconds_tag           3
#define PlayAudio_fade_in_duration_seconds_tag   4
#define PlayAudio_fade_out_duration_seconds_tag  5
#define PlayAudio_timeout_fade_out_duration_seconds_tag 6
#define StopAudio_fade_out_duration_seconds_tag  1
#define VoiceControl_enable_tag                  1
#define Volume_volume_tag                        1

/* Struct field encoding specification for nanopb */
extern const pb_field_t StopAudio_fields[2];
extern const pb_field_t PlayAudio_fields[7];
extern const pb_field_t Volume_fields[2];
extern const pb_field_t VoiceControl_fields[2];

/* Maximum encoded size of messages (where known) */
#define StopAudio_size                           6
#define PlayAudio_size                           96
#define Volume_size                              6
#define VoiceControl_size                        2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
