/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Wed Nov  2 15:35:58 2016. */

#ifndef PB_AUDIO_FEATURES_CONTROL_PB_H_INCLUDED
#define PB_AUDIO_FEATURES_CONTROL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _AudioFeaturesControl {
    bool has_enable_keyword_features;
    bool enable_keyword_features;
} AudioFeaturesControl;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AudioFeaturesControl_init_default        {false, 0}
#define AudioFeaturesControl_init_zero           {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AudioFeaturesControl_enable_keyword_features_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t AudioFeaturesControl_fields[2];

/* Maximum encoded size of messages (where known) */
#define AudioFeaturesControl_size                2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
