/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Tue Oct 28 16:47:21 2014. */

#include "envelope.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t envelope_fields[3] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, envelope, message_type, message_type, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, envelope, message_bytes, message_type, 0),
    PB_LAST_FIELD
};


