/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Tue Oct 28 16:47:21 2014. */

#ifndef PB_ENVELOPE_PB_H_INCLUDED
#define PB_ENVELOPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _envelope_type {
    envelope_type_PERIODIC_DATA = 1,
    envelope_type_AUDIO_DATA = 2
} envelope_type;

/* Struct definitions */
typedef struct _envelope {
    envelope_type message_type;
    pb_callback_t message_bytes;
} envelope;

/* Default values for struct fields */

/* Initializer values for message structs */
#define envelope_init_default                    {(envelope_type)0, {{NULL}, NULL}}
#define envelope_init_zero                       {(envelope_type)0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define envelope_message_type_tag                1
#define envelope_message_bytes_tag               2

/* Struct field encoding specification for nanopb */
extern const pb_field_t envelope_fields[3];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
