/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.9-dev at Tue Aug 26 07:37:33 2014. */

#ifndef _PB_ENVELOPE_PB_H_
#define _PB_ENVELOPE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _envelope_type {
    envelope_type_PERIODIC_DATA = 1,
    envelope_type_AUDIO_DATA = 2
} envelope_type;

/* Struct definitions */
typedef struct _envelope {
    envelope_type message_type;
    pb_callback_t message_bytes;
} envelope;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define envelope_message_type_tag                1
#define envelope_message_bytes_tag               2

/* Struct field encoding specification for nanopb */
extern const pb_field_t envelope_fields[3];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
