/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9-dev at Tue Aug 26 07:37:33 2014. */

#include "envelope.pb.h"



const pb_field_t envelope_fields[3] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, envelope, message_type, message_type, 0),
    PB_FIELD2(  2, BYTES   , REQUIRED, CALLBACK, OTHER, envelope, message_bytes, message_type, 0),
    PB_LAST_FIELD
};


