/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Thu Nov 13 13:17:25 2014. */

#include "filetransfer.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FileMessage_fields[6] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, FileMessage, device_id, device_id, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, FileMessage, unix_time, device_id, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, CALLBACK, OTHER, FileMessage, data, unix_time, 0),
    PB_FIELD(  4, INT64   , OPTIONAL, STATIC  , OTHER, FileMessage, position, data, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, FileMessage, fileid, position, 0),
    PB_LAST_FIELD
};


