/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Thu Mar 26 14:37:12 2015. */

#ifndef PB_LOG_PB_H_INCLUDED
#define PB_LOG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _LogType {
    LogType_UNSTRUCTURED = 1,
    LogType_KEY_VALUE = 2
} LogType;

/* Struct definitions */
typedef struct _sense_log {
    bool has_unix_time;
    int32_t unix_time;
    pb_callback_t device_id;
    pb_callback_t text;
    bool has_property;
    LogType property;
} sense_log;

/* Default values for struct fields */

/* Initializer values for message structs */
#define sense_log_init_default                   {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, (LogType)0}
#define sense_log_init_zero                      {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, (LogType)0}

/* Field tags (for use in manual encoding/decoding) */
#define sense_log_unix_time_tag                  1
#define sense_log_device_id_tag                  2
#define sense_log_text_tag                       3
#define sense_log_property_tag                   4

/* Struct field encoding specification for nanopb */
extern const pb_field_t sense_log_fields[5];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
