/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Thu Nov 13 16:25:55 2014. */

#ifndef PB_LOG_PB_H_INCLUDED
#define PB_LOG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _sense_log {
    bool has_unix_time;
    int32_t unix_time;
    pb_callback_t device_id;
    pb_callback_t text;
} sense_log;

/* Default values for struct fields */

/* Initializer values for message structs */
#define sense_log_init_default                   {false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define sense_log_init_zero                      {false, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define sense_log_unix_time_tag                  1
#define sense_log_device_id_tag                  2
#define sense_log_text_tag                       3

/* Struct field encoding specification for nanopb */
extern const pb_field_t sense_log_fields[4];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
