/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Thu Mar 26 14:37:12 2015. */

#include "log.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t sense_log_fields[5] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, sense_log, unix_time, unix_time, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, sense_log, device_id, unix_time, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, sense_log, text, device_id, 0),
    PB_FIELD(  4, ENUM    , OPTIONAL, STATIC  , OTHER, sense_log, property, text, 0),
    PB_LAST_FIELD
};


