/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.9 at Tue Sep  2 22:39:12 2014. */

#ifndef _PB_MATRIX_PB_H_
#define _PB_MATRIX_PB_H_
#include "../nanopb/pb.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Matrix_DataType {
    Matrix_DataType_FLOAT = 0,
    Matrix_DataType_INT = 1
} Matrix_DataType;

/* Struct definitions */
typedef struct _Matrix {
    pb_callback_t id;
    int32_t rows;
    int32_t cols;
    Matrix_DataType datatype;
    pb_callback_t idata;
    pb_callback_t fdata;
    int64_t time1;
    int64_t time2;
    pb_callback_t tags;
    pb_callback_t source;
} Matrix;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Matrix_init_default                      {{{NULL}, NULL}, 0, 0, (Matrix_DataType)0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Matrix_init_zero                         {{{NULL}, NULL}, 0, 0, (Matrix_DataType)0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Matrix_id_tag                            1
#define Matrix_rows_tag                          2
#define Matrix_cols_tag                          3
#define Matrix_datatype_tag                      4
#define Matrix_idata_tag                         5
#define Matrix_fdata_tag                         6
#define Matrix_time1_tag                         7
#define Matrix_time2_tag                         8
#define Matrix_tags_tag                          9
#define Matrix_source_tag                        10

/* Struct field encoding specification for nanopb */
extern const pb_field_t Matrix_fields[11];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
