/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9 at Wed Aug 27 16:14:31 2014. */

#include "matrix.pb.h"



const pb_field_t Matrix_fields[8] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, Matrix, id, id, 0),
    PB_FIELD2(  2, INT32   , REQUIRED, STATIC  , OTHER, Matrix, rows, id, 0),
    PB_FIELD2(  3, INT32   , REQUIRED, STATIC  , OTHER, Matrix, cols, rows, 0),
    PB_FIELD2(  4, ENUM    , REQUIRED, STATIC  , OTHER, Matrix, datatype, cols, 0),
    PB_FIELD2(  5, SINT32  , REPEATED, CALLBACK, OTHER, Matrix, idata, datatype, 0),
    PB_FIELD2(  6, FLOAT   , REPEATED, CALLBACK, OTHER, Matrix, fdata, idata, 0),
    PB_FIELD2(  7, INT64   , OPTIONAL, STATIC  , OTHER, Matrix, time, fdata, 0),
    PB_LAST_FIELD
};


