/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.8 at Fri Oct 10 12:09:27 2014. */

#include "morpheus_ble.pb.h"



const pb_field_t MorpheusCommand_fields[14] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, MorpheusCommand, version, version, 0),
    PB_FIELD2(  2, ENUM    , REQUIRED, STATIC  , OTHER, MorpheusCommand, type, version, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, deviceId, type, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, accountId, deviceId, 0),
    PB_FIELD2(  5, ENUM    , OPTIONAL, STATIC  , OTHER, MorpheusCommand, error, accountId, 0),
    PB_FIELD2(  6, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, wifiName, error, 0),
    PB_FIELD2(  7, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, wifiSSID, wifiName, 0),
    PB_FIELD2(  8, STRING  , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, wifiPassword, wifiSSID, 0),
    PB_FIELD2(  9, INT32   , OPTIONAL, STATIC  , OTHER, MorpheusCommand, batteryLevel, wifiPassword, 0),
    PB_FIELD2( 10, INT32   , OPTIONAL, STATIC  , OTHER, MorpheusCommand, uptime, batteryLevel, 0),
    PB_FIELD2( 11, INT32   , OPTIONAL, STATIC  , OTHER, MorpheusCommand, motionData, uptime, 0),
    PB_FIELD2( 12, BYTES   , OPTIONAL, CALLBACK, OTHER, MorpheusCommand, motionDataEntrypted, motionData, 0),
    PB_FIELD2( 13, INT32   , OPTIONAL, STATIC  , OTHER, MorpheusCommand, firmwareVersion, motionDataEntrypted, 0),
    PB_LAST_FIELD
};


