/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Tue Jan 26 11:03:07 2016. */

#include "ntp.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t hello_NTPDataPacket_fields[5] = {
    PB_FIELD(  1, INT64   , OPTIONAL, STATIC  , FIRST, hello_NTPDataPacket, reference_ts, reference_ts, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC  , OTHER, hello_NTPDataPacket, origin_ts, reference_ts, 0),
    PB_FIELD(  3, INT64   , OPTIONAL, STATIC  , OTHER, hello_NTPDataPacket, receive_ts, origin_ts, 0),
    PB_FIELD(  4, INT64   , OPTIONAL, STATIC  , OTHER, hello_NTPDataPacket, transmit_ts, receive_ts, 0),
    PB_LAST_FIELD
};


