/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9-dev at Fri Jul 25 14:30:59 2014. */

#include "periodic.pb.h"



const pb_field_t periodic_data_fields[8] = {
    PB_FIELD2(  1, INT32   , OPTIONAL, STATIC  , FIRST, periodic_data, unix_time, unix_time, 0),
    PB_FIELD2(  2, INT32   , OPTIONAL, STATIC  , OTHER, periodic_data, light, unix_time, 0),
    PB_FIELD2(  3, INT32   , OPTIONAL, STATIC  , OTHER, periodic_data, temperature, light, 0),
    PB_FIELD2(  4, INT32   , OPTIONAL, STATIC  , OTHER, periodic_data, humidity, temperature, 0),
    PB_FIELD2(  5, INT32   , OPTIONAL, STATIC  , OTHER, periodic_data, dust, humidity, 0),
    PB_FIELD2(  6, STRING  , OPTIONAL, CALLBACK, OTHER, periodic_data, name, dust, 0),
    PB_FIELD2(  7, BYTES   , OPTIONAL, CALLBACK, OTHER, periodic_data, mac, name, 0),
    PB_LAST_FIELD
};


