/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Wed Apr 01 13:31:11 2015. */

#include "ProvisionRequest.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ProvisonRequest_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, ProvisonRequest, device_id, device_id, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, ProvisonRequest, need_key, device_id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, ProvisonRequest, serial, need_key, 0),
    PB_LAST_FIELD
};


