/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Wed Apr 01 13:27:48 2015. */

#include "ProvisionResponse.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ProvisionResponse_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, ProvisionResponse, key, key, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, ProvisionResponse, retry, key, 0),
    PB_LAST_FIELD
};


