/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Mon Apr 06 13:57:27 2015. */

#include "provision.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ProvisionRequest_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, ProvisionRequest, device_id, device_id, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, ProvisionRequest, need_key, device_id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, ProvisionRequest, serial, need_key, 0),
    PB_LAST_FIELD
};

const pb_field_t ProvisionResponse_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, ProvisionResponse, key, key, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, ProvisionResponse, retry, key, 0),
    PB_LAST_FIELD
};


