/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Mon Apr 06 13:57:27 2015. */

#ifndef PB_PROVISION_PB_H_INCLUDED
#define PB_PROVISION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _ProvisionRequest {
    pb_callback_t device_id;
    bool need_key;
    pb_callback_t serial;
} ProvisionRequest;

typedef PB_BYTES_ARRAY_T(17) ProvisionResponse_key_t;

typedef struct _ProvisionResponse {
    bool has_key;
    ProvisionResponse_key_t key;
    bool has_retry;
    bool retry;
} ProvisionResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ProvisionRequest_init_default            {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ProvisionResponse_init_default           {false, {0, {0}}, false, 0}
#define ProvisionRequest_init_zero               {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ProvisionResponse_init_zero              {false, {0, {0}}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ProvisionRequest_device_id_tag           1
#define ProvisionRequest_need_key_tag            2
#define ProvisionRequest_serial_tag              3
#define ProvisionResponse_key_tag                1
#define ProvisionResponse_retry_tag              2

/* Struct field encoding specification for nanopb */
extern const pb_field_t ProvisionRequest_fields[4];
extern const pb_field_t ProvisionResponse_fields[3];

/* Maximum encoded size of messages (where known) */
#define ProvisionResponse_size                   21

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
