/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Wed Apr 01 13:27:48 2015. */

#ifndef PB_PROVISIONRESPONSE_PB_H_INCLUDED
#define PB_PROVISIONRESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef PB_BYTES_ARRAY_T(17) ProvisionResponse_key_t;

typedef struct _ProvisionResponse {
    bool has_key;
    ProvisionResponse_key_t key;
    bool has_retry;
    bool retry;
} ProvisionResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ProvisionResponse_init_default           {false, {0, {0}}, false, 0}
#define ProvisionResponse_init_zero              {false, {0, {0}}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ProvisionResponse_key_tag                1
#define ProvisionResponse_retry_tag              2

/* Struct field encoding specification for nanopb */
extern const pb_field_t ProvisionResponse_fields[3];

/* Maximum encoded size of messages (where known) */
#define ProvisionResponse_size                   21

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
