/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Fri Jul 22 14:41:03 2016. */

#include "response.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SpeechResponse_fields[5] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, SpeechResponse, url, url, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, SpeechResponse, text, url, 0),
    PB_FIELD(  3, ENUM    , OPTIONAL, STATIC  , OTHER, SpeechResponse, result, text, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, SpeechResponse, audio_stream_size, result, 0),
    PB_LAST_FIELD
};


