/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Fri Jun 10 13:13:22 2016. */

#ifndef PB_RESPONSE_PB_H_INCLUDED
#define PB_RESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _SpeechResponse_Result {
    SpeechResponse_Result_OK = 0,
    SpeechResponse_Result_UNKNOWN = 1,
    SpeechResponse_Result_REJECTED = 2,
    SpeechResponse_Result_TRY_AGAIN = 3
} SpeechResponse_Result;

/* Struct definitions */
typedef struct _SpeechResponse {
    pb_callback_t url;
    pb_callback_t text;
    bool has_result;
    SpeechResponse_Result result;
} SpeechResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SpeechResponse_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, false, (SpeechResponse_Result)0}
#define SpeechResponse_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, false, (SpeechResponse_Result)0}

/* Field tags (for use in manual encoding/decoding) */
#define SpeechResponse_url_tag                   1
#define SpeechResponse_text_tag                  2
#define SpeechResponse_result_tag                3

/* Struct field encoding specification for nanopb */
extern const pb_field_t SpeechResponse_fields[4];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
