/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Mon Nov  3 16:52:50 2014. */

#include "SenseLog.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SenseLog_fields[4] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, SenseLog, unix_time, unix_time, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, SenseLog, device_id, unix_time, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, SenseLog, text, device_id, 0),
    PB_LAST_FIELD
};


