/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Mon Oct 17 17:44:52 2016. */

#include "simple_matrix.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMatrix_fields[5] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, SimpleMatrix, id, id, 0),
    PB_FIELD(  2, SINT32  , OPTIONAL, STATIC  , OTHER, SimpleMatrix, num_cols, id, 0),
    PB_FIELD(  3, ENUM    , OPTIONAL, STATIC  , OTHER, SimpleMatrix, data_type, num_cols, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, CALLBACK, OTHER, SimpleMatrix, payload, data_type, 0),
    PB_LAST_FIELD
};


