/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.9-dev at Tue May 20 15:05:13 2014. */

#ifndef _PB_SIMPLE_PB_H_
#define _PB_SIMPLE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _SimpleMessage {
    int32_t lucky_number;
} SimpleMessage;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define SimpleMessage_lucky_number_tag           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t SimpleMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define SimpleMessage_size                       11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
