/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9-dev at Tue May 20 15:05:13 2014. */

#include "simple.pb.h"



const pb_field_t SimpleMessage_fields[2] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, SimpleMessage, lucky_number, lucky_number, 0),
    PB_LAST_FIELD
};


