/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Mon Jan 25 16:07:09 2016. */

#include "sleep_sounds.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SleepSoundsCommand_fields[1] = {
    PB_LAST_FIELD
};


