/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Sat Oct 01 14:01:38 2016. */

#include "speech.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const Equalizer SpeechRequest_eq_default = Equalizer_SENSE_ONE;
const AudioFormat SpeechRequest_response_default = AudioFormat_MP3;
const int32_t SpeechRequest_sampling_rate_default = 16000;


const pb_field_t SpeechRequest_fields[7] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC  , FIRST, SpeechRequest, word, word, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, SpeechRequest, confidence, word, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, SpeechRequest, version, confidence, 0),
    PB_FIELD(  4, ENUM    , OPTIONAL, STATIC  , OTHER, SpeechRequest, eq, version, &SpeechRequest_eq_default),
    PB_FIELD(  5, ENUM    , OPTIONAL, STATIC  , OTHER, SpeechRequest, response, eq, &SpeechRequest_response_default),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, SpeechRequest, sampling_rate, response, &SpeechRequest_sampling_rate_default),
    PB_LAST_FIELD
};


