/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Tue Apr 12 16:23:35 2016. */

#ifndef PB_STATE_PB_H_INCLUDED
#define PB_STATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _AudioState {
    bool playing_audio;
    bool has_duration_seconds;
    uint32_t duration_seconds;
    bool has_file_path;
    char file_path[64];
    bool has_volume_percent;
    uint32_t volume_percent;
} AudioState;

typedef struct _SenseState {
    pb_callback_t sense_id;
    bool has_audio_state;
    AudioState audio_state;
} SenseState;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AudioState_init_default                  {0, false, 0, false, "", false, 0}
#define SenseState_init_default                  {{{NULL}, NULL}, false, AudioState_init_default}
#define AudioState_init_zero                     {0, false, 0, false, "", false, 0}
#define SenseState_init_zero                     {{{NULL}, NULL}, false, AudioState_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define AudioState_playing_audio_tag             1
#define AudioState_duration_seconds_tag          2
#define AudioState_file_path_tag                 3
#define AudioState_volume_percent_tag            4
#define SenseState_sense_id_tag                  1
#define SenseState_audio_state_tag               2

/* Struct field encoding specification for nanopb */
extern const pb_field_t AudioState_fields[5];
extern const pb_field_t SenseState_fields[3];

/* Maximum encoded size of messages (where known) */
#define AudioState_size                          80

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
