/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Wed Oct 19 14:20:18 2016. */

#include "state.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AudioState_fields[5] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, AudioState, playing_audio, playing_audio, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, AudioState, duration_seconds, playing_audio, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, AudioState, file_path, duration_seconds, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, AudioState, volume_percent, file_path, 0),
    PB_LAST_FIELD
};

const pb_field_t SenseState_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, SenseState, sense_id, sense_id, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, SenseState, audio_state, sense_id, &AudioState_fields),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, SenseState, volume, audio_state, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, SenseState, voice_control_enabled, volume, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SenseState, audio_state) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_AudioState_SenseState)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SenseState, audio_state) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_AudioState_SenseState)
#endif


