/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Thu Nov  6 13:29:33 2014. */

#include "testdata.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TestData_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, CALLBACK, FIRST, TestData, payload, payload, 0),
    PB_LAST_FIELD
};


