################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
audiofeatures.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/audiofeatures.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="audiofeatures.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cmdline.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/cmdline.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="cmdline.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

commands.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/commands.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="commands.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

diskio.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/diskio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="diskio.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

dust_cmd.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/dust_cmd.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="dust_cmd.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

fatfs_cmd.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/fatfs_cmd.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="fatfs_cmd.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

fault.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/fault.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="fault.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

fft.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/fft.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="fft.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

i2c_cmd.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/i2c_cmd.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="i2c_cmd.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/main.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="main.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pinmux.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/pinmux.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="pinmux.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

spi_cmd.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/spi_cmd.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="spi_cmd.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

uartstdio.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/uartstdio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uartstdio.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ustdlib.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/ustdlib.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="ustdlib.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

wifi_cmd.obj: C:/Users/chrisjohnson/Desktop/kitsune/kitsune/wifi_cmd.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib --abi=eabi -me -O1 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/fatfs/src" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/ExtLibs/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/portable/CCS/ARM_CM3/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/third_party/FreeRTOS/source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/oslib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/driverlib/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Source/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/simplelink/Include/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/inc/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/common" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/nanopb" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/protobuf" --include_path="C:/Users/chrisjohnson/Desktop/kitsune/kitsune/main/" -g --no_intrinsics --gcc --define=ccs --define=ARM --define=CC3200_ES_1_2_1 --define=USE_FREERTOS --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --gen_func_subsections=on --preproc_with_compile --preproc_dependency="wifi_cmd.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


